feat(article): add article on exploring recommendation system algorithms
SigmoidAI/articles pull request #10
Opened 2023-08-17 20:52 UTC by vcecan

Uploaded the article about recommendation systems, it is an article about the more used algorithms,the target group of this article are people with little knowledge in ML, or begginers

2023-08-20 11:24 UTC, pyramixofficial commented on exploring_recommendation_system_algorithms/article.md
Please make sure to also add the README.md for your article folder

2023-08-20 11:29 UTC, pyramixofficial commented on exploring_recommendation_system_algorithms/article.md
> +![Figure 2.2 Cosine Similarity formula](https://cdn-images-1.medium.com/max/2000/1*MMb3QqZCFpszitGcBOmMEQ.png)
I would recommend to write the formula in LaTeX formatting rather than image in this kind of cases

2023-08-20 11:32 UTC, pyramixofficial commented on exploring_recommendation_system_algorithms/article.md
> +
Please make sure to add a reference section at the end to showcase all the resources that you used in the creation of this article

2023-08-20 11:33 UTC, pyramixofficial requested changes
Looks promising overall, left some comments, here and there, please make sure to address them

2024-01-18 20:59 UTC, vcecan commented
Made changes, added readme

2024-01-19 10:51 UTC, pyramixofficial approved these changes

2024-01-20 15:57 UTC, merged